id: A8FF88F64
title: E38A
type: translation
source_metadata:
  languages:
  - sa
  - fr
  - en
  - zh
  - bo
  - mon
  datatype: PlainText
  created_at: 2022-08-16 14:22:52.462017
  last_modified_at: 2022-08-16 14:22:52.462028
