id: A8FF88F64
title: Śāntideva Bodhicaryāvatāra
type: translation
source : https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_metadata:
  creation_method: web_scrapping
  languages:
  - mon
  - sa
  - zh
  - en
  - bo
  - fr
  datatype: PlainText
  created_at: 2022-08-16 14:22:52.462017
  last_modified_at: 2022-08-16 14:22:52.462028
